### ISSUE TITLE
Readme links to Sonatype OSS Snapshots broken

### ISSUE THREAD

**Issue by Oliviero50** [180Protocol/codaptor#36]
Hello,
I was trying to get the latest version of Codaptor, with the [ Feature 28: CORS Request support](https://github.com/180Protocol/codaptor/issues/28)

However, it seems that the links to the Sonatype OSS Snapshots in the Readme Section [Versions and Artifacts](https://github.com/180Protocol/codaptor#versions-and-artifacts) are broken. They redirect to the following url  `https://oss.sonatype.org/content/repositories/snapshots/`
with the message _Directory listing forbidden._

Would you be able to fix that please?

Also, do you have any plans as to when a new version will be released? Useful features such as CORS support were implemented since the last release.

Thank you very much for your work. Codaptor truly makes creating REST APIs for CorDapps very easy!

**Comment by parthbond180** [comment]
Hi Oliviero, 
Thanks for your patience with this. We just released a new version `0.4.0-corda4.7`. It has all bug-fixes from the past few months of development including the #28 CORS Request support. We have also updated the [Versions and Artifacts](https://github.com/180Protocol/codaptor#versions-and-artifacts) section of the README with the updated Maven Central links. As for the snapshot URL gicing a `Directory listing forbidden` - SNAPSHOTS can be accessed via [OSS Sonatype Cordaptor](https://oss.sonatype.org/#nexus-search;gav~tech.b180.cordaptor~cordaptor-bundle-rest-embedded). 

Again, thanks for using cordaptor!
